### ISSUE TITLE
i have installed the addon but when i am enabling it, it is giving me an error

### ISSUE THREAD

**Issue by Sh-Mehul** [NevilArt/BsMax_2_80#1]
![Error](https://user-images.githubusercontent.com/59861271/72780221-4c135700-3c44-11ea-8f27-2f750fa01792.png)
Check this screenshot.
I am completely noob to installing the addon so please help.
I am using blender 2.79.

**Comment by NevilArt** [comment]
Hello Dear Mehul
Unfortunately the BsMax add-on works only on Blender version 2.80 and above.
Many APIs changed from 2.79 to 2.80 and it is so hard make add-on work in both version at the same time.

**Comment by NevilArt** [comment]
> 
> 
> ![Error](https://user-images.githubusercontent.com/59861271/72780221-4c135700-3c44-11ea-8f27-2f750fa01792.png)
> Check this screenshot.
> I am completely noob to installing the addon so please help.
> I am using blender 2.79.

Hello Dear Mehul
Unfortunately the BsMax add-on works only on Blender version 2.80 and above.
Many APIs changed from 2.79 to 2.80 and it is so hard make add-on work in both version at the same time.

**Comment by NevilArt** [comment]
> 
> 
> Check this screenshot.
> I am completely noob to installing the addon so please help.
> I am using blender 2.79.

Hello Dear Mehul
Unfortunately the BsMax add-on works only on Blender version 2.80 and above.
Many APIs changed from 2.79 to 2.80 and it is so hard make add-on work in both version at the same time.
