### ISSUE TITLE
BSMAX ISSUE

### ISSUE THREAD

**Issue by Halo-War-Paul** [NevilArt/BsMax_2_80#1]
Hi there

Im following one of your tutorials and installed the BSMAX add on and even though it works, when I right click normally on my object as per your tutorial this pops up - Im not sure if its an issue with your add on or if im just being stupid

Hope this helps :)

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BsMax_2_80-master\tools\public\view\droptool.py", line 64, in execute
    self.call_menu(ctx)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BsMax_2_80-master\tools\public\view\droptool.py", line 57, in call_menu
    if pref.floatmenus == "QuadMenu_st_andkey":
AttributeError: 'NoneType' object has no attribute 'floatmenus'

location: <unknown location>:-1

**Comment by NevilArt** [comment]
Hi
I test the add-on but did not face the error.
looks like you Installed wrong version of the add-on.
download the package from https://github.com/NevilArt/BsMax_2_80
extract the zip file 
Install the "BsMax_2-80_2-92.zip" for old version

or

For new version 3.0+
Download package from https://github.com/NevilArt/BsMax 
Install package itself  as add-on.
