### ISSUE TITLE
3ds max controls behavior incorrect

### ISSUE THREAD

**Issue by tonycstech** [NevilArt/BsMax_2_80#10]
While moving object, press S to activate snaps, makes object go into scale mode.
It should activate snaps instead.
This behavior applies to move and rotate, pressing S while performing either move or rotate, sill turn on scale mode instead.

Moving faces, or extruding faces behaves same way.

**Comment by NevilArt** [comment]
Assign key-map gesture was via puthon not works in Blender 2.8x. If they fix the API I will able do some tests for solve this issue.

Thank you for report.

**Comment by tonycstech** [comment]
Thank you. You are the best.

**Comment by NevilArt** [comment]
Unfortunately disabling the S,R,G keys while transforming object and define other action is not possible via python for now.
but I'll keep this task in my schedule in TODO list till I find the solution.
Blender developers has some plane for update Key-map system. I`ll will check again if they do some changes.
