### ISSUE TITLE
There is a bug in the Max mode operator panel.

### ISSUE THREAD

**Issue by Marcyze** [NevilArt/BsMax_2_80#12]
Hello.
I tried this add-on with Blender 2.83.10.
BsMax is the best.
However, I found one bug.
That is, the operator panel is not working.
The first time it works fine. I have a problem a second time.
For example, if you enter a numerical value when you want to inset a polygon, it will be reflected in the previously selected polygon.
It seems to work fine in Maya mode, but I'm having trouble with Max mode.

I hope this is improved. From Japan.
![Capture](https://user-images.githubusercontent.com/77431255/104557653-f6219580-5684-11eb-96cf-e7d9d3ddb026.jpg)

**Comment by NevilArt** [comment]
Hi Dear Marcyze

I tried the Inset face tool in 2.83.10 and do not face this problem. can you make a short video to explain what exactly happening, maybe I did not understand the issue that you mean.

**Comment by Marcyze** [comment]
Thank you for your reply.
You said no problem. So I tried installing Blender 2.83.10 and Bsmax on another PC.
Then, strangely, Bsmax worked perfectly.
PCs often do that.
However, it remains unknown why it was resolved.
I will post this video for the time being.
Thank you Naser.

https://user-images.githubusercontent.com/77431255/104866169-3a60ae80-5981-11eb-9293-0e309b5000d3.mp4

**Comment by NevilArt** [comment]
By information you give me, I can guess what is the problem. difference between Maya and Max mode is select operator that simulate 3DsMax Element select in Max mode (active with press '5' in edit mesh mode). I`ll try to fix it in next release.

**Comment by Marcyze** [comment]
I understand.
Bsmax is great.
I am very much looking forward to it in the future.

**Comment by NevilArt** [comment]
I did an undo change in mesh select tool. now you can test it and let me know issue fixed or not.

**Comment by Marcyze** [comment]
Thank you.
The problem is gone.
I am surprised at the quick response.

**Comment by NevilArt** [comment]
Nice, I`m happy to hear the problem solved.
Thank you for report the issue. and don`t forget the sharing the 'BsMax' let people how needed this know this add-on exist.
