### ISSUE TITLE
alt+中键旋转物体偶尔失效

### ISSUE THREAD

**Issue by muchfolk** [NevilArt/BsMax_2_80#14]
如题，alt+中键旋转物体失效，需松开中键重新按下才可以选装物体

换句话说，也就是

先alt再按中键，可旋转物体 如果先中间 再alt，只能平移，无法旋转    

可以忽略这个顺序吗？

谢谢~

**Comment by NevilArt** [comment]
你好。 我知道您的意思，但不幸的是目前还不可能。 我希望将来能找到解决该问题的方法。

感谢您的举报。

(Translated by Google Translate and hope there is not miss-translated)

**Comment by muchfolk** [comment]
blender都已经更新到3.0了,不知道这个bug是不是已经优化掉?

**Comment by NevilArt** [comment]
Unfortunately Blender key-map system did not updated yet.
