### ISSUE TITLE
Camera and Light lister

### ISSUE THREAD

**Issue by Nicknroll** [NevilArt/BsMax_2_80#15]
Hi
Thanks for adding such important features!

I'd like to ask, maybe you can add some functionality for them in the next release:

1. For Light Lister add visibility buttons. Also would be nice to have option for spread angle and adding IES map directly from lister.
2. "Make camera active" button for Camera Lister, or make it automatically when you select camera.

Regards
Nick

**Comment by NevilArt** [comment]
Hi Nice.
Yeah those are good ideas. thank you for share them with me. I`ll add those soon as possible.

**Comment by Nicknroll** [comment]
> Hi Nice.
> Yeah those are good ideas. thank you for share them with me. I`ll add those soon as possible.

Glad to hear! Really appreciate your openness to ideas!

Some question: is it possible to pin Lister floating windows, to not hide them automatically?

Also, maybe it is better to optionally hide this parameters?
![Screenshot_1](https://user-images.githubusercontent.com/74839903/117011614-aaa7fb80-acf6-11eb-8901-29865462393b.jpg)
Personally i don't use them here, so we can save some space or put other parameters?

**Comment by NevilArt** [comment]
Unfortunately 'pin floating windows' is not possible in Blender for now.

Yeah im agree with you, I need to change the Lister concept to more optimized and more functionality.

**Comment by Nicknroll** [comment]
Some ideas for light lister, probably you'll find them reasonable to implement:
I guess it would be handy to keep all light sources in a one place, so what if put there world surface and emissive materials?
Last one often used for different types of mesh lights for imitation neon light, LED light etc. Usually i have to search for mesh and necessary material just to slightly adjust value or color, so keeping emissive materials together with all scenes light would be convenient as for me!

**Comment by NevilArt** [comment]
I did some changes.
![Light lister](https://user-images.githubusercontent.com/36098311/117566381-0ab7ec80-b0bf-11eb-81eb-17147a39ad75.jpg)
Light Lister has full control on light now.
I`ll work on emitter materials next weekend.
 
 
![Camera lister](https://user-images.githubusercontent.com/36098311/117566388-13102780-b0bf-11eb-8d58-1295f937d9f8.jpg)
For Camera Lister, had to make better one. for now just add 'make active' tool.

**Comment by NevilArt** [comment]
Blender Lights do not have On/Off but it lights off when is hide. I can put Hide/Unhide button in light Lister.

For make a 'preinstalled Blender add-on' I had to make a perfect tool first. current tool is not looks complete. for now my add-on  can help people. whene any of my tools become perfect I will be happy to commit it to blender itself.
