### ISSUE TITLE
Check this plz

### ISSUE THREAD

**Issue by istake** [NevilArt/BsMax_2_80#2]
![1](https://user-images.githubusercontent.com/25282782/76780585-a964f800-67f0-11ea-8c6e-c0b114ef1527.png)

this messages show up when I try to check this box

![2](https://user-images.githubusercontent.com/25282782/76780588-aa962500-67f0-11ea-9c9f-76e1af116bbb.png)

I don't know what can I do

↓ This is my system info from Blender

[system-info.txt](https://github.com/NevilArt/BsMax_2_80/files/4339286/system-info.txt)

**Comment by NevilArt** [comment]
Thank you for report. problem solved and add-on updated.

This command works on all other version but Blender 2.8a
    bpy.context.window_manager.keyconfigs['blender'].preferences['select_mouse']
looks like this is a blender bug and I had to report it to developers.

**Comment by istake** [comment]
I see, Thank you :)
