### ISSUE TITLE
Menu Font is tiny

### ISSUE THREAD

**Issue by Gusher** [NevilArt/BsMax_2_80#21]
Am using latest Blender 2.93.5 and have UI scaled to 200, but the font for the plugin doesn't scale up, stays very small..

https://ibb.co/W2cVB86

**Comment by NevilArt** [comment]
There is an option under the add-on setting. you can scale the menu there
![Capture](https://user-images.githubusercontent.com/36098311/140983739-e3bc8941-265b-4c35-8f3d-270e526340ff.JPG)
.

**Comment by Gusher** [comment]
oh ok, it's all there I see.... this is fantastic... feels alot like 3dsmax like this...
