### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by poudink** [NevilArt/BsMax_2_80#3]
I must be missing something. I have set every possible option (Navigation, Keymap and Tools Pack) to 3DsMax but only the keymap one seems to be doing anything. I don't have the 3DS Max right click menu and primitive objects I've seen in your videos. This is using the portable windows version of blender available at blender.org/download which I think is 2.82

**Comment by NevilArt** [comment]
you have to chose the Quad menu (with Keymap) to active the 3DsMax right click menu
![Quad menu](https://user-images.githubusercontent.com/36098311/77816002-5e8c8f80-70d0-11ea-8c16-bc68697196e1.jpg)
The Primitive objects moved to "Create" menu there are not in "Add" menu any more.
![create](https://user-images.githubusercontent.com/36098311/77816052-c0e59000-70d0-11ea-94f1-fb56036118e3.jpg)
