### ISSUE TITLE
Key map lost track

### ISSUE THREAD

**Issue by jintat87** [NevilArt/BsMax_2_80#5]
Hi, first of all thank you for your hard work making this addon. It's vary helpful especially for me migrating from max. 

Everything is working well with few tinkering but one major issue I have is everytime I open blender, Eventhough the addon is enabled, I have to go back to preference to re-select the navigation, keymap, float menu etc to 3ds max for the keymap to work normally.

I'm not sure it's only me cos I don't see anyone reporting it. Is this an issue can be fix or it's just the way blender re-mapped the keys after addon were loaded? I'm using Blender 2.83.

Thanks.
![2020_06_17_17_03_55_Blender_Preferences](https://user-images.githubusercontent.com/16854451/84878667-b8dc3180-b0bc-11ea-843e-c7990a66254e.png)

**Comment by NevilArt** [comment]
Hi, thank you for report the issue. I did some changes and looks like its solved. can you please test the updated version and let me know is it happen again or not?

**Comment by jintat87** [comment]
Hi, I've tried it and now it work flawlessly. Thank you for the fix!
