### ISSUE TITLE
Shade Smooth Problem

### ISSUE THREAD

**Issue by hansnolte** [NevilArt/BsMax_2_80#9]
Hi nevilart,

great addon.

I have a little problem with primitives and shade smooth.

For example, I create a cone.
Give him
Shade Smooth
Normal->Auto Smooth

Each time the parameters (Radius1, Radius2 etc.) are changed, the cone jumps back to Shade Flat.
Calling Shade Smooth again is not a problem, but it does not work if you use the cone (or any other primitive) would like to animate (Animatable).

A tip would be nice.

Blender 2.91
BsMax 0.1.0.20201013

**Comment by NevilArt** [comment]
Hi Hansnolte

Generating the new mesh clears the all mesh setting. I had to tray so save the setting before generate and restore after.
you can check the result in the next update.

**Comment by hansnolte** [comment]
Hi nevilart,
great!
I'm really looking forward to the next update.

Many greetings
Hans
